[img2catalog]
optin = "healthdata_catalog"
# optout = "exclude_catalog"
remove_optin = true

[dataset]
# Theme should be Health, according to the EU Data Theme vocabulary
theme = "http://publications.europa.eu/resource/authority/data-theme/HEAL"
# Default License for datasets is "available upon reasonable request"
license = "http://example.com/license#nolicense"

[dataset.contact_point]
# override = true
full_name = "Health-RI servicedesk"
email = "mailto:datamanager@example.com"
identifier = "http://example.com"

[dataset.publisher]
name = ["Health-RI"]
identifier = "http://health-ri.nl"

[catalog]
title = "Example XNAT catalog"
description = "This is an example XNAT catalog description"

[catalog.publisher]
name = ["Example publishing institution"]
identifier = "http://www.example.com/institution#example"

[distribution.default]
title = "XNAT imaging distribution"
description = "Link to XNAT instance where the imaging data can be accessed."
